# Generated by Django 4.1.1 on 2022-09-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petregister',
            name='pet_type',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
