# Generated by Django 4.1.1 on 2022-09-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_petregister_pet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petregister',
            name='pet_image',
            field=models.ImageField(upload_to='pets/images/'),
        ),
    ]
